version: '2'
services: 
  web:
    build: .
    ports: 
      - "5000:5000"
    volumes: 
      - .:/counter_app
    links: 
      - db:mongodb
    container_name: counterapp_web_2
    depends_on: 
      - db
  db:
    image: mongo:3.0.2
    restart: always
    container_name: counterapp_db_2